using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using _8anu.Api.Common;
using _8anu.Api.Managers.Interfaces;

namespace _8anu.Api.Controllers
{
    [ApiVersion("1.0")]
    [Route("api/v{version:apiVersion}/[controller]")]
    public class [PLURAL]Controller : Controller
    {
        private I[PLURAL]Manager _[L-PLURAL]Manager;
        public [PLURAL]Controller(I[PLURAL]Manager [L-PLURAL]Manager)
        {
            _[L-PLURAL]Manager = [L-PLURAL]Manager;

            // THIS FILE IS GENERATED BY A TEMPLATE
            //
            // To make builds work, please make changes to following files
            // 
            // File:
            // /8anu.Api.Business/Startup.cs
            // Function:
            // ConfigureServices
            // Code:
            // services.AddTransient<I[PLURAL]Manager, [PLURAL]Manager>();
            //
            // File:
            // /8anu.Api.Data/Contexts/DomainModelMySqlContext.cs
            // Code (property):
            // public DbSet<[SINGULAR]> [PLURAL] { get; set; }
            //
            // File:
            // /8anu.Api.Data/Startup.cs
            // Function:
            // ConfigureServices
            // Code:
            // services.AddTransient<I[PLURAL]Repository, [PLURAL]Repository>();
            //
            // File:
            // /8anu.Data.Migration/migrationsettings.json
            // Code:
            /*
            {
              "Name": "[L-PLURAL]",
              "Skip": false,
              "GeneratorClass": "_8anu.Data.Migration.Generators.[PLURAL]",
              "ModelTypeName": "_8anu.Api.Common.[SINGULAR], 8anu.Api.Common",
              "DbSetName": "[PLURAL]"
            },
            */
            //
            // After you have made the changes, run:
            /*
            # navigate to migration project folder
            cd 8anu.Data.Migration
            
            # run migration project
            dotnet run
            
            # navigate to 8anu.Api folder
            cd ../8anu.Api 
            
            # add dildoes migration to entity framework migrations
            dotnet ef migrations add Add[PLURAL]
            
            # run api
            dotnet run 
            */

            // now you should be able to see your shit at
            // /api/v1.0/[L-PLURAL]/getall
        }

        // GET api/values
        [HttpGet("getall")]
        public List<[SINGULAR]> GetAll()
        {  
            return _[L-PLURAL]Manager.GetAll();
        }
    }
}