using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using _8anu.Api.Common.DataEntities;
using _8anu.Api.Managers.Interfaces;

namespace _8anu.Api.Controllers
{
    [ApiVersion("1.0")]
    [Route("api/v{version:apiVersion}/[controller]")]
    public class BouldersController : Controller
    {
        private IBouldersManager _bouldersManager;
        public BouldersController(IBouldersManager bouldersManager)
        {
            _bouldersManager = bouldersManager;

            // THIS FILE IS GENERATED BY A TEMPLATE
            //
            // To make builds work, please make changes to following files
            // 
            // File:
            // /8anu.Api.Business/Startup.cs
            // Function:
            // ConfigureServices
            // Code:
            // services.AddTransient<IBouldersManager, BouldersManager>();
            //
            // File:
            // /8anu.Api.Data/Contexts/DomainModelMySqlContext.cs
            // Code (property):
            // public DbSet<Boulder> Boulders { get; set; }
            //
            // File:
            // /8anu.Api.Data/Startup.cs
            // Function:
            // ConfigureServices
            // Code:
            // services.AddTransient<IBouldersRepository, BouldersRepository>();
            //
            // File:
            // /8anu.Data.Migration/migrationsettings.json
            // Code:
            /*
            {
              "Name": "boulders",
              "Skip": false,
              "GeneratorClass": "_8anu.Data.Migration.Generators.Boulders",
              "ModelTypeName": "_8anu.Api.Common.Boulder, 8anu.Api.Common",
              "DbSetName": "Boulders"
            },
            */
            //
            // After you have made the changes, run:
            /*
            # navigate to migration project folder
            cd 8anu.Data.Migration
            
            # run migration project
            dotnet run
            
            # navigate to 8anu.Api folder
            cd ../8anu.Api 
            
            # add dildoes migration to entity framework migrations
            dotnet ef migrations add AddBoulders
            
            # run api
            dotnet run 
            */

            // now you should be able to see your shit at
            // /api/v1.0/boulders/getall
        }

        // GET api/values
        [HttpGet("getall")]
        public List<Boulder> GetAll()
        {  
            return _bouldersManager.GetAll();
        }
    }
}