using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using _8anu.Api.Common.DataEntities;
using _8anu.Api.Managers.Interfaces;

namespace _8anu.Api.Controllers
{
    [ApiVersion("1.0")]
    [Route("api/v{version:apiVersion}/[controller]")]
    public class GradingSystemsController : Controller
    {
        private IGradingSystemsManager _gradingsystemsManager;
        public GradingSystemsController(IGradingSystemsManager gradingsystemsManager)
        {
            _gradingsystemsManager = gradingsystemsManager;

            // THIS FILE IS GENERATED BY A TEMPLATE
            //
            // To make builds work, please make changes to following files
            // 
            // File:
            // /8anu.Api.Business/Startup.cs
            // Function:
            // ConfigureServices
            // Code:
            // services.AddTransient<IGradingSystemsManager, GradingSystemsManager>();
            //
            // File:
            // /8anu.Api.Data/Contexts/DomainModelMySqlContext.cs
            // Code (property):
            // public DbSet<GradingSystem> GradingSystems { get; set; }
            //
            // File:
            // /8anu.Api.Data/Startup.cs
            // Function:
            // ConfigureServices
            // Code:
            // services.AddTransient<IGradingSystemsRepository, GradingSystemsRepository>();
            //
            // File:
            // /8anu.Data.Migration/migrationsettings.json
            // Code:
            /*
            {
                "Skip": false,
                "Name": "gradingsystems",
                "GeneratorClass": "_8anu.Data.Migration.Generators.GradingSystems",
                "ModelTypeName": "_8anu.Api.Common.GradingSystem, 8anu.Api.Common",
                "DbSetName": "GradingSystems"
            },
            */
            //
            // After you have made the changes, run:
            /*
            # navigate to migration project folder
            cd 8anu.Data.Migration
            
            # run migration project
            dotnet run
            
            # navigate to 8anu.Api folder
            cd ../8anu.Api 
            
            # add dildoes migration to entity framework migrations
            dotnet ef migrations add AddGradingSystems
            
            # run api
            dotnet run 
            */

            // now you should be able to see your shit at
            // /api/v1.0/gradingsystems/getall
        }

        // GET api/values
        [HttpGet("getall")]
        public List<GradingSystem> GetAll()
        {  
            return _gradingsystemsManager.GetAll();
        }
    }
}